# Use official Node image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy dependency files first (better caching)
COPY package.json ./

# Install dependencies
RUN npm install 

# Copy source code
COPY . .

# Expose app port
EXPOSE 5000

# Start the app
CMD ["node", "server.js"]
